version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: betechnet-postgres
    environment:
      POSTGRES_DB: BETECH_DB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admmin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d BETECH_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./tomcat-login-app
    container_name: betechnet-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BETECH_DB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admmin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./tomcat-login-frontend
    container_name: betechnet-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  postgres_data: