apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: betech-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true