# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rds-postgres-secret
type: Opaque
data:
  # username: admin (base64 encoded)
  username: YWRtaW4=
  # password: admin123 (base64 encoded)
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS betech_db;
    GRANT ALL PRIVILEGES ON DATABASE betech_db TO admin;
