# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betechnet-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: betechnet-backend
  template:
    metadata:
      labels:
        app: betechnet-backend
    spec:
      serviceAccountName: betechnet-backend
      automountServiceAccountToken: false
      containers:
        - name: betechnet-backend
          image: 374965156099.dkr.ecr.us-west-2.amazonaws.com/betech-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://betechnet-postgres:5432/betech_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgres-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: betechnet-backend
spec:
  selector:
    app: betechnet-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: betechnet-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
subjects:
  - kind: ServiceAccount
    name: betechnet-backend
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io